quarkus-home-dir=${kc.home.dir}
credential-keystore-name=csstore.jceks
keystore-name=../conf/truststores/keycloak-sso.p12
keystore-password=MASK-15aa1KqpkA/i6NVMtwzkCm;12345678;50
truststore-name=../conf/truststores/keycloak-sso-truststore.jks
truststore-password=MASK-15aa1KqpkA/i6NVMtwzkCm;12345678;50

cbgl.persistence.jdbc.url=jdbc:oracle:thin:@centraldb-19c.modernisc.com:1521:centraldb
cbgl.persistence.jdbc.user=cbgl
cbgl.persistence.jdbc.password=cbgl
cbgl.persistence.jdbc.driver=oracle.jdbc.OracleDriver
cbgl.hibernate.dialect=org.hibernate.dialect.OracleDialect

quarkus.datasource.oracle.jdbc.url=jdbc:oracle:thin:@centraldb-19c.modernisc.com:1521:centraldb
quarkus.datasource.oracle.username=cbgl
quarkus.datasource.oracle.password=cbgl
quarkus.datasource.oracle.jdbc.driver=oracle.jdbc.OracleDriver
quarkus.datasource.oracle.hibernate.dialect=org.hibernate.dialect.OracleDialect
quarkus.datasource.jdbc.background-validation-interval=30s
quarkus.datasource.jdbc.validation-query-sql=SELECT 1 FROM DUAL

# ???? ??????? ?????
quarkus.datasource.jdbc.idle-removal-interval=5m
quarkus.datasource.jdbc.max-lifetime=30m

# ????? ??????? ????
quarkus.datasource.jdbc.min-size=5
quarkus.datasource.jdbc.max-size=20
