quarkus-home-dir=${kc.home.dir}
credential-keystore-name=csstore.jceks
keystore-name=keycloak-sso.p12
keystore-password=MASK-15aa1KqpkA/i6NVMtwzkCm;12345678;50
truststore-name=keycloak-sso-truststore.jks
truststore-password=MASK-15aa1KqpkA/i6NVMtwzkCm;12345678;50
remove-facility-job-threshold-days=1
nakisa-url=http://core2.dev.modernisc.com:7070/nakisa/keycloak/1.0
auth-server-url=http://172.31.65.70:8095/auth/realms/misc-services/protocol/openid-connect/token
auth-server-clientId=keycloak-app
auth-server-clientSecret=MASK-2UfaMTawo/8n5kpzKEDXfoXARbvo6Kfk7UZuZSK.1XJw8DnFp/DVwH;12345678;50
