quarkus-home-dir=${kc.home.dir}
credential-keystore-name=csstore.jceks
keystore-name=../conf/truststores/keycloak-sso.p12
keystore-password=MASK-15aa1KqpkA/i6NVMtwzkCm;12345678;50
truststore-name=../conf/truststores/keycloak-sso-truststore.jks
truststore-password=MASK-15aa1KqpkA/i6NVMtwzkCm;12345678;50
misc.iam.url=http://172.31.65.55:9096/iam/api/keycloak
misc.iam.auth-server-url=http://172.31.65.70:8095/auth/realms/iam/protocol/openid-connect/token
misc.iam.auth-server-clientId=keycloak-app
misc.iam.auth-server-clientSecret=MASK-0Fzy3V.lCTnEx13XU6L3HnvVQSMlZ7ZWyKoMqr4cNAmD32nv6p3zfF;12345678;50